/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const TrainStation = IDL.Record({
  'code' : IDL.Text,
  'name' : IDL.Text,
  'location' : IDL.Text,
});
export const TrainStopTime = IDL.Record({
  'arrivalTime' : IDL.Opt(IDL.Text),
  'station' : TrainStation,
  'departureTime' : IDL.Opt(IDL.Text),
});
export const TrainRoute = IDL.Record({
  'destination' : TrainStation,
  'trainNumber' : IDL.Text,
  'origin' : TrainStation,
  'trainName' : IDL.Text,
  'stops' : IDL.Vec(TrainStation),
  'schedule' : IDL.Vec(TrainStopTime),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ComplaintStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'pending' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Complaint = IDL.Record({
  'id' : IDL.Text,
  'status' : ComplaintStatus,
  'latitude' : IDL.Opt(IDL.Float64),
  'userId' : IDL.Principal,
  'description' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'feedback' : IDL.Opt(IDL.Text),
  'longitude' : IDL.Opt(IDL.Float64),
  'category' : IDL.Text,
  'rating' : IDL.Opt(IDL.Nat),
  'photo' : IDL.Opt(ExternalBlob),
  'location' : IDL.Text,
});
export const VehicleType = IDL.Variant({
  'bus' : IDL.Null,
  'car' : IDL.Null,
  'fireTruck' : IDL.Null,
  'train' : IDL.Null,
  'truck' : IDL.Null,
  'other' : IDL.Text,
  'bike' : IDL.Null,
  'ambulance' : IDL.Null,
  'police' : IDL.Null,
});
export const Vehicle = IDL.Record({
  'id' : IDL.Text,
  'latitude' : IDL.Float64,
  'vehicleType' : VehicleType,
  'name' : IDL.Text,
  'longitude' : IDL.Float64,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComplaintRating' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'addOrUpdateVehicleLocation' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Int],
      [],
      [],
    ),
  'addTrainRoute' : IDL.Func([TrainRoute], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getAllTrainRoutes' : IDL.Func([], [IDL.Vec(TrainRoute)], ['query']),
  'getAllVehicleLocations' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComplaint' : IDL.Func([IDL.Text], [Complaint], ['query']),
  'getComplaintsByStatus' : IDL.Func(
      [ComplaintStatus],
      [IDL.Vec(Complaint)],
      ['query'],
    ),
  'getLatestVehicleLocations' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Vehicle)],
      ['query'],
    ),
  'getServiceLinks' : IDL.Func(
      [],
      [
        IDL.Record({
          'propertyTaxURL' : IDL.Text,
          'waterBillURL' : IDL.Text,
          'electricityBoardURL' : IDL.Text,
          'deathCertsURL' : IDL.Text,
          'birthCertsURL' : IDL.Text,
          'tradeLicenseRenewalURL' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getTrainRoute' : IDL.Func([IDL.Text], [TrainRoute], ['query']),
  'getTrainsBetweenStations' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(TrainRoute)],
      ['query'],
    ),
  'getTrainsByStation' : IDL.Func([IDL.Text], [IDL.Vec(TrainRoute)], ['query']),
  'getUserComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVehicleLocation' : IDL.Func([IDL.Text], [Vehicle], ['query']),
  'getVehicleLocations' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getVehicleLocationsInBounds' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Vec(Vehicle)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeVehicleLocation' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitComplaint' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
      ],
      [IDL.Text],
      [],
    ),
  'updateComplaintStatus' : IDL.Func([IDL.Text, ComplaintStatus], [], []),
  'updateVehicleLocationWithHistory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, VehicleType, IDL.Int],
      [IDL.Opt(Vehicle)],
      [],
    ),
  'uploadComplaintPhoto' : IDL.Func(
      [IDL.Text, ExternalBlob, IDL.Text],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const TrainStation = IDL.Record({
    'code' : IDL.Text,
    'name' : IDL.Text,
    'location' : IDL.Text,
  });
  const TrainStopTime = IDL.Record({
    'arrivalTime' : IDL.Opt(IDL.Text),
    'station' : TrainStation,
    'departureTime' : IDL.Opt(IDL.Text),
  });
  const TrainRoute = IDL.Record({
    'destination' : TrainStation,
    'trainNumber' : IDL.Text,
    'origin' : TrainStation,
    'trainName' : IDL.Text,
    'stops' : IDL.Vec(TrainStation),
    'schedule' : IDL.Vec(TrainStopTime),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ComplaintStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'pending' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Complaint = IDL.Record({
    'id' : IDL.Text,
    'status' : ComplaintStatus,
    'latitude' : IDL.Opt(IDL.Float64),
    'userId' : IDL.Principal,
    'description' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'feedback' : IDL.Opt(IDL.Text),
    'longitude' : IDL.Opt(IDL.Float64),
    'category' : IDL.Text,
    'rating' : IDL.Opt(IDL.Nat),
    'photo' : IDL.Opt(ExternalBlob),
    'location' : IDL.Text,
  });
  const VehicleType = IDL.Variant({
    'bus' : IDL.Null,
    'car' : IDL.Null,
    'fireTruck' : IDL.Null,
    'train' : IDL.Null,
    'truck' : IDL.Null,
    'other' : IDL.Text,
    'bike' : IDL.Null,
    'ambulance' : IDL.Null,
    'police' : IDL.Null,
  });
  const Vehicle = IDL.Record({
    'id' : IDL.Text,
    'latitude' : IDL.Float64,
    'vehicleType' : VehicleType,
    'name' : IDL.Text,
    'longitude' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComplaintRating' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'addOrUpdateVehicleLocation' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Int],
        [],
        [],
      ),
    'addTrainRoute' : IDL.Func([TrainRoute], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getAllTrainRoutes' : IDL.Func([], [IDL.Vec(TrainRoute)], ['query']),
    'getAllVehicleLocations' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComplaint' : IDL.Func([IDL.Text], [Complaint], ['query']),
    'getComplaintsByStatus' : IDL.Func(
        [ComplaintStatus],
        [IDL.Vec(Complaint)],
        ['query'],
      ),
    'getLatestVehicleLocations' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Vehicle)],
        ['query'],
      ),
    'getServiceLinks' : IDL.Func(
        [],
        [
          IDL.Record({
            'propertyTaxURL' : IDL.Text,
            'waterBillURL' : IDL.Text,
            'electricityBoardURL' : IDL.Text,
            'deathCertsURL' : IDL.Text,
            'birthCertsURL' : IDL.Text,
            'tradeLicenseRenewalURL' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getTrainRoute' : IDL.Func([IDL.Text], [TrainRoute], ['query']),
    'getTrainsBetweenStations' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(TrainRoute)],
        ['query'],
      ),
    'getTrainsByStation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TrainRoute)],
        ['query'],
      ),
    'getUserComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVehicleLocation' : IDL.Func([IDL.Text], [Vehicle], ['query']),
    'getVehicleLocations' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getVehicleLocationsInBounds' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Vec(Vehicle)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeVehicleLocation' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitComplaint' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
        ],
        [IDL.Text],
        [],
      ),
    'updateComplaintStatus' : IDL.Func([IDL.Text, ComplaintStatus], [], []),
    'updateVehicleLocationWithHistory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, VehicleType, IDL.Int],
        [IDL.Opt(Vehicle)],
        [],
      ),
    'uploadComplaintPhoto' : IDL.Func(
        [IDL.Text, ExternalBlob, IDL.Text],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };