/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Complaint {
  'id' : string,
  'status' : ComplaintStatus,
  'latitude' : [] | [number],
  'userId' : Principal,
  'description' : string,
  'photoUrl' : [] | [string],
  'feedback' : [] | [string],
  'longitude' : [] | [number],
  'category' : string,
  'rating' : [] | [bigint],
  'photo' : [] | [ExternalBlob],
  'location' : string,
}
export type ComplaintStatus = { 'resolved' : null } |
  { 'pending' : null } |
  { 'inProgress' : null };
export type ExternalBlob = Uint8Array;
export interface TrainRoute {
  'destination' : TrainStation,
  'trainNumber' : string,
  'origin' : TrainStation,
  'trainName' : string,
  'stops' : Array<TrainStation>,
  'schedule' : Array<TrainStopTime>,
}
export interface TrainStation {
  'code' : string,
  'name' : string,
  'location' : string,
}
export interface TrainStopTime {
  'arrivalTime' : [] | [string],
  'station' : TrainStation,
  'departureTime' : [] | [string],
}
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'address' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vehicle {
  'id' : string,
  'latitude' : number,
  'vehicleType' : VehicleType,
  'name' : string,
  'longitude' : number,
  'timestamp' : bigint,
}
export type VehicleType = { 'bus' : null } |
  { 'car' : null } |
  { 'fireTruck' : null } |
  { 'train' : null } |
  { 'truck' : null } |
  { 'other' : string } |
  { 'bike' : null } |
  { 'ambulance' : null } |
  { 'police' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComplaintRating' : ActorMethod<[string, bigint, string], undefined>,
  'addOrUpdateVehicleLocation' : ActorMethod<
    [string, string, number, number, VehicleType, bigint],
    undefined
  >,
  'addTrainRoute' : ActorMethod<[TrainRoute], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllComplaints' : ActorMethod<[], Array<Complaint>>,
  'getAllTrainRoutes' : ActorMethod<[], Array<TrainRoute>>,
  'getAllVehicleLocations' : ActorMethod<[], Array<Vehicle>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComplaint' : ActorMethod<[string], Complaint>,
  'getComplaintsByStatus' : ActorMethod<[ComplaintStatus], Array<Complaint>>,
  'getLatestVehicleLocations' : ActorMethod<[bigint], Array<Vehicle>>,
  'getServiceLinks' : ActorMethod<
    [],
    {
      'propertyTaxURL' : string,
      'waterBillURL' : string,
      'electricityBoardURL' : string,
      'deathCertsURL' : string,
      'birthCertsURL' : string,
      'tradeLicenseRenewalURL' : string,
    }
  >,
  'getTrainRoute' : ActorMethod<[string], TrainRoute>,
  'getTrainsBetweenStations' : ActorMethod<[string, string], Array<TrainRoute>>,
  'getTrainsByStation' : ActorMethod<[string], Array<TrainRoute>>,
  'getUserComplaints' : ActorMethod<[], Array<Complaint>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVehicleLocation' : ActorMethod<[string], Vehicle>,
  'getVehicleLocations' : ActorMethod<[], Array<Vehicle>>,
  'getVehicleLocationsInBounds' : ActorMethod<
    [number, number, number, number],
    Array<Vehicle>
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeVehicleLocation' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitComplaint' : ActorMethod<
    [string, string, string, [] | [ExternalBlob], [] | [number], [] | [number]],
    string
  >,
  'updateComplaintStatus' : ActorMethod<[string, ComplaintStatus], undefined>,
  'updateVehicleLocationWithHistory' : ActorMethod<
    [string, string, number, number, VehicleType, bigint],
    [] | [Vehicle]
  >,
  'uploadComplaintPhoto' : ActorMethod<[string, ExternalBlob, string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];