/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TrainStation {
    code: string;
    name: string;
    location: string;
}
export type VehicleType = {
    __kind__: "bus";
    bus: null;
} | {
    __kind__: "car";
    car: null;
} | {
    __kind__: "fireTruck";
    fireTruck: null;
} | {
    __kind__: "train";
    train: null;
} | {
    __kind__: "truck";
    truck: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "bike";
    bike: null;
} | {
    __kind__: "ambulance";
    ambulance: null;
} | {
    __kind__: "police";
    police: null;
};
export interface TrainStopTime {
    arrivalTime?: string;
    station: TrainStation;
    departureTime?: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface TrainRoute {
    destination: TrainStation;
    trainNumber: string;
    origin: TrainStation;
    trainName: string;
    stops: Array<TrainStation>;
    schedule: Array<TrainStopTime>;
}
export interface Complaint {
    id: string;
    status: ComplaintStatus;
    latitude?: number;
    userId: Principal;
    description: string;
    photoUrl?: string;
    feedback?: string;
    longitude?: number;
    category: string;
    rating?: bigint;
    photo?: ExternalBlob;
    location: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Vehicle {
    id: string;
    latitude: number;
    vehicleType: VehicleType;
    name: string;
    longitude: number;
    timestamp: bigint;
}
export interface UserProfile {
    name: string;
    email?: string;
    address?: string;
    phone?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ComplaintStatus {
    resolved = "resolved",
    pending = "pending",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addComplaintRating(complaintId: string, rating: bigint, feedback: string): Promise<void>;
    addOrUpdateVehicleLocation(vehicleId: string, latitude: number, longitude: number, timestamp: bigint): Promise<void>;
    addTrainRoute(route: TrainRoute): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllComplaints(): Promise<Array<Complaint>>;
    getAllTrainRoutes(): Promise<Array<TrainRoute>>;
    getAllVehicleLocations(): Promise<Array<Vehicle>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getComplaint(complaintId: string): Promise<Complaint>;
    getComplaintsByStatus(status: ComplaintStatus): Promise<Array<Complaint>>;
    getLatestVehicleLocations(count: bigint): Promise<Array<Vehicle>>;
    getServiceLinks(): Promise<{
        propertyTaxURL: string;
        waterBillURL: string;
        electricityBoardURL: string;
        deathCertsURL: string;
        birthCertsURL: string;
        tradeLicenseRenewalURL: string;
    }>;
    getTrainRoute(trainNumber: string): Promise<TrainRoute>;
    getTrainsBetweenStations(originCode: string, destinationCode: string): Promise<Array<TrainRoute>>;
    getTrainsByStation(stationCode: string): Promise<Array<TrainRoute>>;
    getUserComplaints(): Promise<Array<Complaint>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVehicleLocation(vehicleId: string): Promise<Vehicle>;
    getVehicleLocations(): Promise<Array<Vehicle>>;
    getVehicleLocationsInBounds(north: number, south: number, east: number, west: number): Promise<Array<Vehicle>>;
    isCallerAdmin(): Promise<boolean>;
    removeVehicleLocation(vehicleId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitComplaint(description: string, category: string, location: string, photo: ExternalBlob | null, latitude: number | null, longitude: number | null): Promise<string>;
    updateComplaintStatus(complaintId: string, status: ComplaintStatus): Promise<void>;
    updateVehicleLocationWithHistory(vehicleId: string, name: string, latitude: number, longitude: number, vehicleType: VehicleType, timestamp: bigint): Promise<Vehicle | null>;
    uploadComplaintPhoto(complaintId: string, photo: ExternalBlob, photoUrl: string): Promise<string>;
}
import type { Complaint as _Complaint, ComplaintStatus as _ComplaintStatus, ExternalBlob as _ExternalBlob, TrainRoute as _TrainRoute, TrainStation as _TrainStation, TrainStopTime as _TrainStopTime, UserProfile as _UserProfile, UserRole as _UserRole, Vehicle as _Vehicle, VehicleType as _VehicleType, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addComplaintRating(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addComplaintRating(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComplaintRating(arg0, arg1, arg2);
            return result;
        }
    }
    async addOrUpdateVehicleLocation(arg0: string, arg1: number, arg2: number, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateVehicleLocation(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateVehicleLocation(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addTrainRoute(arg0: TrainRoute): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrainRoute(to_candid_TrainRoute_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrainRoute(to_candid_TrainRoute_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllComplaints(): Promise<Array<Complaint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllComplaints();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllComplaints();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTrainRoutes(): Promise<Array<TrainRoute>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrainRoutes();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrainRoutes();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVehicleLocations(): Promise<Array<Vehicle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVehicleLocations();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVehicleLocations();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComplaint(arg0: string): Promise<Complaint> {
        if (this.processError) {
            try {
                const result = await this.actor.getComplaint(arg0);
                return from_candid_Complaint_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComplaint(arg0);
            return from_candid_Complaint_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComplaintsByStatus(arg0: ComplaintStatus): Promise<Array<Complaint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComplaintsByStatus(to_candid_ComplaintStatus_n40(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComplaintsByStatus(to_candid_ComplaintStatus_n40(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestVehicleLocations(arg0: bigint): Promise<Array<Vehicle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestVehicleLocations(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestVehicleLocations(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServiceLinks(): Promise<{
        propertyTaxURL: string;
        waterBillURL: string;
        electricityBoardURL: string;
        deathCertsURL: string;
        birthCertsURL: string;
        tradeLicenseRenewalURL: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceLinks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceLinks();
            return result;
        }
    }
    async getTrainRoute(arg0: string): Promise<TrainRoute> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrainRoute(arg0);
                return from_candid_TrainRoute_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrainRoute(arg0);
            return from_candid_TrainRoute_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrainsBetweenStations(arg0: string, arg1: string): Promise<Array<TrainRoute>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrainsBetweenStations(arg0, arg1);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrainsBetweenStations(arg0, arg1);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrainsByStation(arg0: string): Promise<Array<TrainRoute>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrainsByStation(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrainsByStation(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserComplaints(): Promise<Array<Complaint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserComplaints();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserComplaints();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVehicleLocation(arg0: string): Promise<Vehicle> {
        if (this.processError) {
            try {
                const result = await this.actor.getVehicleLocation(arg0);
                return from_candid_Vehicle_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVehicleLocation(arg0);
            return from_candid_Vehicle_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVehicleLocations(): Promise<Array<Vehicle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVehicleLocations();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVehicleLocations();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVehicleLocationsInBounds(arg0: number, arg1: number, arg2: number, arg3: number): Promise<Array<Vehicle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVehicleLocationsInBounds(arg0, arg1, arg2, arg3);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVehicleLocationsInBounds(arg0, arg1, arg2, arg3);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeVehicleLocation(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeVehicleLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeVehicleLocation(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n42(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n42(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitComplaint(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob | null, arg4: number | null, arg5: number | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitComplaint(arg0, arg1, arg2, await to_candid_opt_n44(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n46(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n46(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitComplaint(arg0, arg1, arg2, await to_candid_opt_n44(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n46(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n46(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateComplaintStatus(arg0: string, arg1: ComplaintStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateComplaintStatus(arg0, to_candid_ComplaintStatus_n40(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateComplaintStatus(arg0, to_candid_ComplaintStatus_n40(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateVehicleLocationWithHistory(arg0: string, arg1: string, arg2: number, arg3: number, arg4: VehicleType, arg5: bigint): Promise<Vehicle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVehicleLocationWithHistory(arg0, arg1, arg2, arg3, to_candid_VehicleType_n47(this._uploadFile, this._downloadFile, arg4), arg5);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVehicleLocationWithHistory(arg0, arg1, arg2, arg3, to_candid_VehicleType_n47(this._uploadFile, this._downloadFile, arg4), arg5);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async uploadComplaintPhoto(arg0: string, arg1: ExternalBlob, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadComplaintPhoto(arg0, await to_candid_ExternalBlob_n45(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadComplaintPhoto(arg0, await to_candid_ExternalBlob_n45(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
}
function from_candid_ComplaintStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ComplaintStatus): ComplaintStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_Complaint_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Complaint): Promise<Complaint> {
    return await from_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_TrainRoute_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrainRoute): TrainRoute {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_TrainStopTime_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrainStopTime): TrainStopTime {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleType): VehicleType {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Vehicle_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Vehicle): Vehicle {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Vehicle]): Vehicle | null {
    return value.length === 0 ? null : from_candid_Vehicle_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ComplaintStatus;
    latitude: [] | [number];
    userId: Principal;
    description: string;
    photoUrl: [] | [string];
    feedback: [] | [string];
    longitude: [] | [number];
    category: string;
    rating: [] | [bigint];
    photo: [] | [_ExternalBlob];
    location: string;
}): Promise<{
    id: string;
    status: ComplaintStatus;
    latitude?: number;
    userId: Principal;
    description: string;
    photoUrl?: string;
    feedback?: string;
    longitude?: number;
    category: string;
    rating?: bigint;
    photo?: ExternalBlob;
    location: string;
}> {
    return {
        id: value.id,
        status: from_candid_ComplaintStatus_n18(_uploadFile, _downloadFile, value.status),
        latitude: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.latitude)),
        userId: value.userId,
        description: value.description,
        photoUrl: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.photoUrl)),
        feedback: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.feedback)),
        longitude: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.longitude)),
        category: value.category,
        rating: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.rating)),
        photo: record_opt_to_undefined(await from_candid_opt_n22(_uploadFile, _downloadFile, value.photo)),
        location: value.location
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    destination: _TrainStation;
    trainNumber: string;
    origin: _TrainStation;
    trainName: string;
    stops: Array<_TrainStation>;
    schedule: Array<_TrainStopTime>;
}): {
    destination: TrainStation;
    trainNumber: string;
    origin: TrainStation;
    trainName: string;
    stops: Array<TrainStation>;
    schedule: Array<TrainStopTime>;
} {
    return {
        destination: value.destination,
        trainNumber: value.trainNumber,
        origin: value.origin,
        trainName: value.trainName,
        stops: value.stops,
        schedule: from_candid_vec_n27(_uploadFile, _downloadFile, value.schedule)
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    arrivalTime: [] | [string];
    station: _TrainStation;
    departureTime: [] | [string];
}): {
    arrivalTime?: string;
    station: TrainStation;
    departureTime?: string;
} {
    return {
        arrivalTime: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.arrivalTime)),
        station: value.station,
        departureTime: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.departureTime))
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    latitude: number;
    vehicleType: _VehicleType;
    name: string;
    longitude: number;
    timestamp: bigint;
}): {
    id: string;
    latitude: number;
    vehicleType: VehicleType;
    name: string;
    longitude: number;
    timestamp: bigint;
} {
    return {
        id: value.id,
        latitude: value.latitude,
        vehicleType: from_candid_VehicleType_n33(_uploadFile, _downloadFile, value.vehicleType),
        name: value.name,
        longitude: value.longitude,
        timestamp: value.timestamp
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
    address: [] | [string];
    phone: [] | [string];
}): {
    name: string;
    email?: string;
    address?: string;
    phone?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.email)),
        address: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.address)),
        phone: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    pending: null;
} | {
    inProgress: null;
}): ComplaintStatus {
    return "resolved" in value ? ComplaintStatus.resolved : "pending" in value ? ComplaintStatus.pending : "inProgress" in value ? ComplaintStatus.inProgress : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bus: null;
} | {
    car: null;
} | {
    fireTruck: null;
} | {
    train: null;
} | {
    truck: null;
} | {
    other: string;
} | {
    bike: null;
} | {
    ambulance: null;
} | {
    police: null;
}): {
    __kind__: "bus";
    bus: null;
} | {
    __kind__: "car";
    car: null;
} | {
    __kind__: "fireTruck";
    fireTruck: null;
} | {
    __kind__: "train";
    train: null;
} | {
    __kind__: "truck";
    truck: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "bike";
    bike: null;
} | {
    __kind__: "ambulance";
    ambulance: null;
} | {
    __kind__: "police";
    police: null;
} {
    return "bus" in value ? {
        __kind__: "bus",
        bus: value.bus
    } : "car" in value ? {
        __kind__: "car",
        car: value.car
    } : "fireTruck" in value ? {
        __kind__: "fireTruck",
        fireTruck: value.fireTruck
    } : "train" in value ? {
        __kind__: "train",
        train: value.train
    } : "truck" in value ? {
        __kind__: "truck",
        truck: value.truck
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "bike" in value ? {
        __kind__: "bike",
        bike: value.bike
    } : "ambulance" in value ? {
        __kind__: "ambulance",
        ambulance: value.ambulance
    } : "police" in value ? {
        __kind__: "police",
        police: value.police
    } : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Complaint>): Promise<Array<Complaint>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Complaint_n16(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TrainRoute>): Array<TrainRoute> {
    return value.map((x)=>from_candid_TrainRoute_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TrainStopTime>): Array<TrainStopTime> {
    return value.map((x)=>from_candid_TrainStopTime_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Vehicle>): Array<Vehicle> {
    return value.map((x)=>from_candid_Vehicle_n31(_uploadFile, _downloadFile, x));
}
function to_candid_ComplaintStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ComplaintStatus): _ComplaintStatus {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_TrainRoute_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrainRoute): _TrainRoute {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_TrainStopTime_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrainStopTime): _TrainStopTime {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleType_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): _VehicleType {
    return to_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n45(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    arrivalTime?: string;
    station: TrainStation;
    departureTime?: string;
}): {
    arrivalTime: [] | [string];
    station: _TrainStation;
    departureTime: [] | [string];
} {
    return {
        arrivalTime: value.arrivalTime ? candid_some(value.arrivalTime) : candid_none(),
        station: value.station,
        departureTime: value.departureTime ? candid_some(value.departureTime) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
    address?: string;
    phone?: string;
}): {
    name: string;
    email: [] | [string];
    address: [] | [string];
    phone: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        address: value.address ? candid_some(value.address) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    destination: TrainStation;
    trainNumber: string;
    origin: TrainStation;
    trainName: string;
    stops: Array<TrainStation>;
    schedule: Array<TrainStopTime>;
}): {
    destination: _TrainStation;
    trainNumber: string;
    origin: _TrainStation;
    trainName: string;
    stops: Array<_TrainStation>;
    schedule: Array<_TrainStopTime>;
} {
    return {
        destination: value.destination,
        trainNumber: value.trainNumber,
        origin: value.origin,
        trainName: value.trainName,
        stops: value.stops,
        schedule: to_candid_vec_n10(_uploadFile, _downloadFile, value.schedule)
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ComplaintStatus): {
    resolved: null;
} | {
    pending: null;
} | {
    inProgress: null;
} {
    return value == ComplaintStatus.resolved ? {
        resolved: null
    } : value == ComplaintStatus.pending ? {
        pending: null
    } : value == ComplaintStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "bus";
    bus: null;
} | {
    __kind__: "car";
    car: null;
} | {
    __kind__: "fireTruck";
    fireTruck: null;
} | {
    __kind__: "train";
    train: null;
} | {
    __kind__: "truck";
    truck: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "bike";
    bike: null;
} | {
    __kind__: "ambulance";
    ambulance: null;
} | {
    __kind__: "police";
    police: null;
}): {
    bus: null;
} | {
    car: null;
} | {
    fireTruck: null;
} | {
    train: null;
} | {
    truck: null;
} | {
    other: string;
} | {
    bike: null;
} | {
    ambulance: null;
} | {
    police: null;
} {
    return value.__kind__ === "bus" ? {
        bus: value.bus
    } : value.__kind__ === "car" ? {
        car: value.car
    } : value.__kind__ === "fireTruck" ? {
        fireTruck: value.fireTruck
    } : value.__kind__ === "train" ? {
        train: value.train
    } : value.__kind__ === "truck" ? {
        truck: value.truck
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "bike" ? {
        bike: value.bike
    } : value.__kind__ === "ambulance" ? {
        ambulance: value.ambulance
    } : value.__kind__ === "police" ? {
        police: value.police
    } : value;
}
function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TrainStopTime>): Array<_TrainStopTime> {
    return value.map((x)=>to_candid_TrainStopTime_n11(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
